#!/bin/bash

# Debug log prints in case wm has issues
#set -xv
#exec 2>>/tmp/bspwm.log

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-2 connected') ]]; then
    xrandr --output HDMI-2 --mode 2560x1080 --rotate normal --output eDP-1 --primary --mode 1366x768 --rotate normal --right-of HDMI-2
    #xrandr --output HDMI-2 --mode 1920x1080 --rotate normal --output eDP-1 --primary --mode 1366x768 --rotate normal --right-of HDMI-2
    bspc monitor HDMI-2 -d 1 2 3 4 5
    bspc monitor eDP-1 -d 6 7 8 9 10
    #bspc monitor eDP-1 -d 1 2 3 4 5
    #bspc monitor HDMI-2 -d 6 7 8 9 10
else
    xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

feh --bg-center /home/seal/background.jpg

bspc config border_width         0
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^1'
bspc rule -a spotify desktop='^2'

# VMWare Copy-paste support
vmware-user-suid-wrapper

discord
/home/seal/.config/polybar/monitors.sh
