#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then
    xrandr --output eDP --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 3440x1440 --rotate normal --right-of eDP
    bspc monitor eDP -d 1 2 3 4 5
    bspc monitor HDMI-1-0 -d 6 7 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

feh --bg-center /home/seal/background.jpg

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

monitors
